test-environment:
    enabled: ${TEST_ENVIRONMENT_ENABLED}


user-verification: ${USER_VERIFICATION}

jwt-properties:
    issuer: "someone"

cors-configuration-properties:
    allowedOriginPatterns:
        - "*"
    allowedMethods:
        - "*"
    allowedHeaders:
        - "*"
    urlPattern: "/**"

jks-props:
    privateKeyPath: "private.pem"
    publicKeyPath: "public.pem"
    keyId: "jwt-key"
    password: "01123581321Sasha"

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=backend_oaforest&ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    profiles:
        active: dev
    jackson:
        default-property-inclusion: non_null
    liquibase:
        enabled: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: sasha192.bunin@gmail.com
        password: pczo lekf wcia kyxt
        properties:
            smtp:
                auth: true
                starttls:
                    enable: true



